export type Locale = 'en' | 'es'

export const messages = {
  en: {
    skip:'Skip to main content', language:'Language', english:'English', spanish:'Español', value:'Reliable email infrastructure built for growing teams.',
    benefit1:'Send securely through SMTP or API', benefit2:'Track delivery activity with clarity', benefit3:'Manage domains and teams in one place', security:'Identity is protected by Keycloak. Klyrow never stores your password.',
    loginTitle:'Welcome back', loginBody:'Sign in to manage your sending, domains, activity, and team.', google:'Continue with Google', divider:'or continue with email', email:'Email address', workEmail:'Work email', password:'Password', show:'Show', hide:'Hide', keep:'Keep me signed in', keepHint:'This preference will apply when session policy is enabled.', forgot:'Forgot password?', signIn:'Sign in', newUser:'New to Klyrow?', createLink:'Create an account',
    signupTitle:'Create your Klyrow account', signupBody:'Start with one secure workspace for your email operations.', signupDivider:'or create an account with email', first:'First name', last:'Last name', confirm:'Confirm password', termsPrefix:'I agree to the', terms:'Terms of Service', conjunction:'and', privacy:'Privacy Policy', create:'Create account', existing:'Already have an account?', signInLink:'Sign in',
    passwordGuide:'Use at least 12 characters with uppercase, lowercase, a number, and a symbol.', strength:'Password strength', weak:'Weak', fair:'Fair', strong:'Strong',
    verifyTitle:'Check your inbox', verifyBody:'We sent a verification link to {email}. Open the link to finish creating your Klyrow account.', resend:'Resend verification email', different:'Use a different email', returnLogin:'Return to sign in', resent:'A new verification email is on its way.', expiredVerifyTitle:'Verification link expired', expiredVerifyBody:'For your security, verification links expire. Request a new one to continue.', verifiedTitle:'Email verified', verifiedBody:'Your email is verified. You can now continue to Klyrow.', continueLogin:'Continue to sign in',
    forgotTitle:'Reset your password', forgotBody:'Enter your email address and Klyrow will send password-reset instructions when an eligible account exists.', sendReset:'Send reset instructions', sentTitle:'Check your email for the next step.', sentBody:'If an eligible account exists, password-reset instructions are on the way.', resetTitle:'Choose a new password', resetBody:'Create a strong password you do not use elsewhere.', updatePassword:'Update password', resetExpiredTitle:'Reset link expired', resetExpiredBody:'Password-reset links expire for your protection. Request a new one.', resetSuccessTitle:'Password updated', resetSuccessBody:'Your password has been updated. Sign in with your new password.',
    inviteTitle:'Join your Klyrow team', inviteBody:'Enter the invitation code from your workspace invitation.', inviteCode:'Invitation code', validateInvite:'Validate invitation', inviteValid:'Invitation validated. Continue through Keycloak to join your workspace.', inviteInvalid:'This invitation is invalid or has expired.',
    loggedOutTitle:'You’re signed out', loggedOutBody:'Your Klyrow session has ended.', serviceTitle:'Authentication unavailable', serviceBody:'Klyrow authentication is temporarily unavailable. Please try again later.', disabledTitle:'Account unavailable', disabledBody:'This account is disabled or suspended. Contact your administrator.',
    required:'This field is required.', invalidEmail:'Enter a valid email address.', mismatch:'Passwords do not match.', weakPassword:'Choose a stronger password.', acceptTerms:'Accept the Terms and Privacy Policy to continue.', invalidCredentials:'Email or password is incorrect.', rateLimited:'Too many attempts. Try again later.', unavailable:'Klyrow authentication is temporarily unavailable.', duplicate:'An account may already exist. Try signing in or resetting your password.', loading:'Please wait…', errorIcon:'Error:', statusIcon:'Status:', termsLabel:'Terms of Service', privacyLabel:'Privacy Policy', termsPageTitle:'Terms of Service', termsPageBody:'The rules for using Klyrow securely and responsibly.', privacyPageTitle:'Privacy Policy', privacyPageBody:'How Klyrow handles account, workspace, security, and email-operation data.'
  },
  es: {
    skip:'Saltar al contenido principal', language:'Idioma', english:'English', spanish:'Español', value:'Infraestructura de correo confiable para equipos en crecimiento.',
    benefit1:'Envía de forma segura por SMTP o API', benefit2:'Sigue la actividad de entrega con claridad', benefit3:'Gestiona dominios y equipos en un solo lugar', security:'Keycloak protege tu identidad. Klyrow nunca almacena tu contraseña.',
    loginTitle:'Te damos la bienvenida', loginBody:'Inicia sesión para gestionar tus envíos, dominios, actividad y equipo.', google:'Continuar con Google', divider:'o continuar con correo', email:'Correo electrónico', workEmail:'Correo de trabajo', password:'Contraseña', show:'Mostrar', hide:'Ocultar', keep:'Mantener mi sesión iniciada', keepHint:'Esta preferencia se aplicará cuando se habilite la política de sesión.', forgot:'¿Olvidaste tu contraseña?', signIn:'Iniciar sesión', newUser:'¿Primera vez en Klyrow?', createLink:'Crear una cuenta',
    signupTitle:'Crea tu cuenta de Klyrow', signupBody:'Comienza con un espacio seguro para tus operaciones de correo.', signupDivider:'o crear una cuenta con correo', first:'Nombre', last:'Apellido', confirm:'Confirmar contraseña', termsPrefix:'Acepto los', terms:'Términos del servicio', conjunction:'y la', privacy:'Política de privacidad', create:'Crear cuenta', existing:'¿Ya tienes una cuenta?', signInLink:'Iniciar sesión',
    passwordGuide:'Usa al menos 12 caracteres con mayúscula, minúscula, número y símbolo.', strength:'Seguridad de la contraseña', weak:'Débil', fair:'Aceptable', strong:'Fuerte',
    verifyTitle:'Revisa tu bandeja de entrada', verifyBody:'Enviamos un enlace de verificación a {email}. Ábrelo para terminar de crear tu cuenta de Klyrow.', resend:'Reenviar correo de verificación', different:'Usar otro correo', returnLogin:'Volver a iniciar sesión', resent:'Te enviamos un nuevo correo de verificación.', expiredVerifyTitle:'El enlace de verificación venció', expiredVerifyBody:'Por tu seguridad, los enlaces vencen. Solicita uno nuevo para continuar.', verifiedTitle:'Correo verificado', verifiedBody:'Tu correo está verificado. Ya puedes continuar a Klyrow.', continueLogin:'Continuar para iniciar sesión',
    forgotTitle:'Restablece tu contraseña', forgotBody:'Ingresa tu correo y Klyrow enviará instrucciones cuando exista una cuenta elegible.', sendReset:'Enviar instrucciones', sentTitle:'Revisa tu correo para continuar.', sentBody:'Si existe una cuenta elegible, las instrucciones están en camino.', resetTitle:'Elige una nueva contraseña', resetBody:'Crea una contraseña segura que no uses en otros sitios.', updatePassword:'Actualizar contraseña', resetExpiredTitle:'El enlace venció', resetExpiredBody:'Los enlaces vencen para protegerte. Solicita uno nuevo.', resetSuccessTitle:'Contraseña actualizada', resetSuccessBody:'Tu contraseña fue actualizada. Inicia sesión con la nueva contraseña.',
    inviteTitle:'Únete a tu equipo de Klyrow', inviteBody:'Ingresa el código de tu invitación al espacio de trabajo.', inviteCode:'Código de invitación', validateInvite:'Validar invitación', inviteValid:'Invitación validada. Continúa mediante Keycloak para unirte.', inviteInvalid:'La invitación no es válida o venció.',
    loggedOutTitle:'Cerraste sesión', loggedOutBody:'Tu sesión de Klyrow ha terminado.', serviceTitle:'Autenticación no disponible', serviceBody:'La autenticación de Klyrow no está disponible temporalmente. Inténtalo más tarde.', disabledTitle:'Cuenta no disponible', disabledBody:'Esta cuenta está deshabilitada o suspendida. Contacta a tu administrador.',
    required:'Este campo es obligatorio.', invalidEmail:'Ingresa un correo válido.', mismatch:'Las contraseñas no coinciden.', weakPassword:'Elige una contraseña más segura.', acceptTerms:'Acepta los Términos y la Política de privacidad para continuar.', invalidCredentials:'El correo o la contraseña no son correctos.', rateLimited:'Demasiados intentos. Inténtalo más tarde.', unavailable:'La autenticación de Klyrow no está disponible temporalmente.', duplicate:'Es posible que ya exista una cuenta. Inicia sesión o restablece tu contraseña.', loading:'Espera…', errorIcon:'Error:', statusIcon:'Estado:', termsLabel:'Términos del servicio', privacyLabel:'Política de privacidad', termsPageTitle:'Términos del servicio', termsPageBody:'Las reglas para usar Klyrow de forma segura y responsable.', privacyPageTitle:'Política de privacidad', privacyPageBody:'Cómo Klyrow gestiona datos de cuenta, espacio de trabajo, seguridad y operaciones de correo.'
  }
} as const

export type MessageKey = keyof typeof messages.en
